"""empty message

Revision ID: 1f9910a3627
Revises: 492c321bc0c
Create Date: 2016-03-12 10:49:17.949396

"""

# revision identifiers, used by Alembic.
revision = '1f9910a3627'
down_revision = '492c321bc0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
