"""empty message

Revision ID: 490ad28f0b4
Revises: 252d12832ba
Create Date: 2016-03-09 15:28:38.800987

"""

# revision identifiers, used by Alembic.
revision = '490ad28f0b4'
down_revision = '252d12832ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
