"""empty message

Revision ID: 492c321bc0c
Revises: 542afc5352a
Create Date: 2016-03-11 23:04:08.547945

"""

# revision identifiers, used by Alembic.
revision = '492c321bc0c'
down_revision = '542afc5352a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
