"""empty message

Revision ID: 542afc5352a
Revises: 490ad28f0b4
Create Date: 2016-03-11 22:19:08.844281

"""

# revision identifiers, used by Alembic.
revision = '542afc5352a'
down_revision = '490ad28f0b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
